### ISSUE TITLE
void callback hell

### ISSUE THREAD

**Issue by JeffreyChan** [damienbod/AspNetCoreOpeniddictAngularImplicitFlow#1]
I think you can void callback hell with using rxjs or promise, co library in  AuthorizedCallback method

**Comment by damienbod** [comment]
What do you mean? The redirct is returned with a hash. Don't see how I can avoid this, or why I should, What's the problem with this?

Greetings Damien

**Comment by JeffreyChan** [comment]
sorry, I mean this:

![image](https://cloud.githubusercontent.com/assets/5321225/24939744/fd69ef52-1f71-11e7-8de6-b75cbc796fb2.png)

it's callback hell.

**Comment by damienbod** [comment]
Ye, could clean this up, thanks for the pointer,  each validation step must be done.

Greetings Damien

**Comment by JeffreyChan** [comment]
thank you for providing the wonderful demo, sometimes i would use it.

**Comment by damienbod** [comment]
this has been fixed
